## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░

# Prompt Layout - Only modules listed here will show up!
format = """$directory$git_branch$git_status$character"""
right_format = """$nodejs$python$golang$java$cmd_duration"""
add_newline = false

# ============================================
# ACTIVE MODULES
# ============================================

[character]
success_symbol = '[❯](bold #7bf1a8)'
error_symbol = '[❯](bold #fb2c36)'
vimcmd_symbol = '[❮](bold #7bf1a8)'

[directory]
format = '[$path]($style) '
style = 'bold #fcc800'
truncation_length = 3
truncate_to_repo = false
home_symbol = ' '

[git_branch]
format = '[\[$symbol$branch\]]($style) '
symbol = '󰊢 '
style = 'bold #ffa1ad'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = 'bold #d1d5dc'
conflicted = '='
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
up_to_date = ''
untracked = '?${count}'
stashed = '\$'
modified = '!${count}'
staged = '+${count}'
renamed = '»${count}'
deleted = '✘${count}'

[cmd_duration]
min_time = 1000
format = '[\[⏱ $duration\]]($style)'
style = 'bold #fcc800'

# ============================================
# LANGUAGE MODULES
# ============================================

[nodejs]
format = '[\[$symbol$version\]]($style) '
symbol = ' '
style = 'bold #a6e3a1'

[python]
format = '[\[$symbol$version\]]($style) '
symbol = ' '
style = 'bold #fcc800'

[golang]
format = '[\[$symbol$version\]]($style) '
symbol = ' '
style = 'bold cyan'

[java]
format = '[\[$symbol$version\]]($style) '
symbol = ' '
style = 'bold #f38ba8'
